version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      weekly-batch:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/packages/core-ts-array"
      - "/packages/core-ts-async-iterable"
      - "/packages/core-ts-error"
      - "/packages/core-ts-iterable"
      - "/packages/core-ts-loadable"
      - "/packages/core-ts-nullish"
      - "/packages/core-ts-number"
      - "/packages/core-ts-record"
      - "/packages/core-ts-string"
      - "/packages/core-ts-type"
    schedule:
      interval: "weekly"
    groups:
      dev-dependencies:
        dependency-type: "development"
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]